name: RPG_plugin
version: 0.1
author: sG.wolf
description: "sG.wolf's RPG plugin(Beta)"

main: main.Main

commands:
  RPG:
    description: "RPG manage"
  class:
    description: "Select Class"
  trash:
    description: "throw trash!"